"""Keep the <head> of every page consistent: icons, canonical URL, share cards.

Each page keeps its own <title> and <meta name="description"> - those are
written by hand. This script derives the social-share tags from them so a link
pasted into LinkedIn, Slack or an email renders properly instead of as a blank
grey box.

The generated block is fenced by HTML comments and replaced wholesale on every
run, so this is safe to re-run after adding new pages:

    python tools/rewrite_head.py
"""

from __future__ import annotations

import re
import sys
from html import escape, unescape
from pathlib import Path

from media_common import REPO, html_files, rel_url

SITE = "https://daniel.bryars.com"
START = "    <!-- head:meta - generated by tools/rewrite_head.py -->"
END = "    <!-- /head:meta -->"

BLOCK_RE = re.compile(
    re.escape(START.strip()) + r".*?" + re.escape(END.strip()),
    re.DOTALL,
)
TITLE_RE = re.compile(r"<title>(.*?)</title>", re.DOTALL | re.IGNORECASE)
DESC_RE = re.compile(r'<meta\s+name="description"\s+content="([^"]*)"', re.IGNORECASE)

# Pages that should advertise a project-specific share image rather than the
# generic cover. Keyed by path relative to the repo root.
PAGE_IMAGES = {
    "index.html": "images/og-cover.jpg",
    "cool-projects/DriftTrike.html": "project-assets/drift-trike/01-finished-trike-on-grass.jpg",
    "cool-projects/CortenBalustrade.html": "project-assets/corten-ballustrade/08-finished-curve.jpg",
    "cool-projects/LatheSparks.html": "project-assets/lathe-sparks/05-sparks-hero.jpg",
    "cool-projects/MegaBookCase.html": "project-assets/mega-book-case/04-loaded-bookcase-wide.jpg",
    "cool-projects/SpiralStairCase.html": "project-assets/spiral-staircase/01-finished-staircase-full.jpg",
    "cool-projects/CurvingSkirtingBoard.html": "project-assets/curving-skirting-board/01-steam-box-on-terrace.jpg",
    "cool-projects/VintageStringLights.html": "project-assets/vintage-string-lights/01-finished-string-lights-wide.jpg",
    "cool-projects/MotorisedStandingDesk.html": "project-assets/desk-project/06-father-son-finished-top.jpg",
    "cool-projects/BellyBoard.html": "project-assets/belly-board/selected/06-finished-grain-detail.jpg",
    "cool-projects/CVInABox.html": "images/CV-Box.jpg",
}

PERSON_JSONLD = """    <script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "Person",
      "name": "Daniel Bryars",
      "url": "https://daniel.bryars.com/",
      "jobTitle": "Staff Engineer",
      "description": "Engineer and founder working on AI, robotics and systems that have to survive contact with the physical world.",
      "address": { "@type": "PostalAddress", "addressLocality": "Oxford", "addressCountry": "GB" },
      "alumniOf": { "@type": "CollegeOrUniversity", "name": "University of Leeds" },
      "sameAs": [
        "https://github.com/DanielBryars",
        "https://www.linkedin.com/in/danielbryars/",
        "https://stackoverflow.com/users/418246/daniel-james-bryars"
      ]
    }
    </script>
"""


def canonical_for(page: Path) -> str:
    rel = page.relative_to(REPO).as_posix()
    if rel == "index.html":
        return f"{SITE}/"
    if rel.endswith("/index.html"):
        return f"{SITE}/{rel[: -len('index.html')]}"
    return f"{SITE}/{rel}"


def build_block(page: Path, title: str, description: str) -> str:
    rel = page.relative_to(REPO).as_posix()
    image = PAGE_IMAGES.get(rel, "images/og-cover.jpg")
    root = rel_url(page, REPO / "x")[:-1]  # relative prefix back to the repo root

    lines = [
        START,
        f'    <link rel="canonical" href="{canonical_for(page)}">',
        f'    <link rel="icon" href="{root}favicon.svg" type="image/svg+xml">',
        f'    <link rel="apple-touch-icon" href="{root}images/apple-touch-icon.png">',
        '    <meta name="theme-color" content="#10120f">',
        '    <meta name="author" content="Daniel Bryars">',
        '    <meta property="og:type" content="website">',
        '    <meta property="og:site_name" content="Daniel Bryars">',
        f'    <meta property="og:url" content="{canonical_for(page)}">',
        f'    <meta property="og:title" content="{escape(title, quote=True)}">',
        f'    <meta property="og:description" content="{escape(description, quote=True)}">',
        f'    <meta property="og:image" content="{SITE}/{image}">',
        '    <meta name="twitter:card" content="summary_large_image">',
        f'    <meta name="twitter:title" content="{escape(title, quote=True)}">',
        f'    <meta name="twitter:description" content="{escape(description, quote=True)}">',
        f'    <meta name="twitter:image" content="{SITE}/{image}">',
    ]
    if rel == "index.html":
        lines.append(PERSON_JSONLD.rstrip("\n"))
    lines.append(END)
    return "\n".join(lines)


def main() -> int:
    changed = 0
    for page in html_files():
        text = page.read_text(encoding="utf-8")

        title_match = TITLE_RE.search(text)
        desc_match = DESC_RE.search(text)
        if not title_match:
            print(f"  skip (no <title>): {page.relative_to(REPO)}")
            continue
        if not desc_match:
            print(f"  !! no meta description: {page.relative_to(REPO)}")
            continue

        title = unescape(title_match.group(1).strip())
        description = unescape(desc_match.group(1).strip())
        block = build_block(page, title, description)

        if BLOCK_RE.search(text):
            updated = BLOCK_RE.sub(lambda _: block.strip(), text, count=1)
        else:
            # Insert straight after the description tag so the head stays readable.
            insert_at = desc_match.end()
            insert_at = text.index("\n", insert_at) + 1
            updated = text[:insert_at] + block + "\n" + text[insert_at:]

        if updated != text:
            page.write_text(updated, encoding="utf-8")
            changed += 1
            print(f"  head {page.relative_to(REPO)}")

    print(f"{changed} page(s) updated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
