"""Keep the <head> of every page consistent: icons, canonical URL, share cards.

Each page keeps its own <title> and <meta name="description"> - those are
written by hand. This script derives the social-share tags from them so a link
pasted into LinkedIn, Slack or an email renders properly instead of as a blank
grey box.

The generated block is fenced by HTML comments and replaced wholesale on every
run, so this is safe to re-run after adding new pages:

    python tools/rewrite_head.py
"""

from __future__ import annotations

import re
import sys
from html import escape, unescape
from pathlib import Path

from media_common import REPO, html_files, rel_url

SITE = "https://daniel.bryars.com"
START = "    <!-- head:meta - generated by tools/rewrite_head.py -->"
END = "    <!-- /head:meta -->"

BLOCK_RE = re.compile(
    re.escape(START.strip()) + r".*?" + re.escape(END.strip()),
    re.DOTALL,
)
TITLE_RE = re.compile(r"<title>(.*?)</title>", re.DOTALL | re.IGNORECASE)
DESC_RE = re.compile(r'<meta\s+name="description"\s+content="([^"]*)"', re.IGNORECASE)

# Pages that should advertise a project-specific share image rather than the
# generic cover. Keyed by path relative to the repo root.
PAGE_IMAGES = {
    "index.html": "images/og-cover.jpg",
    "projects/index.html": "images/og-cover.jpg",
    "projects/3d-printers/index.html": "projects/3d-printers/images/01-prusa-mk4-toolhead.jpg",
    "projects/active-speakers/index.html": "projects/active-speakers/images/01-speakers-measurement-bench.jpg",
    "projects/belly-board/index.html": "projects/belly-board/images/selected/06-finished-grain-detail.jpg",
    "projects/chess-board/index.html": "projects/chess-board/images/ChessProjectElectromagnets.jpg",
    "projects/corten-balustrade/index.html": "projects/corten-balustrade/images/08-finished-curve.jpg",
    "projects/curving-skirting-board/index.html": "projects/curving-skirting-board/images/01-steam-box-on-terrace.jpg",
    "projects/cv-in-a-box/index.html": "projects/cv-in-a-box/images/CV-Box.jpg",
    "projects/drift-trike/index.html": "projects/drift-trike/images/01-finished-trike-on-grass.jpg",
    "projects/lathe-sparks/index.html": "projects/lathe-sparks/images/05-sparks-hero.jpg",
    "projects/mega-book-case/index.html": "projects/mega-book-case/images/04-loaded-bookcase-wide.jpg",
    "projects/motorised-standing-desk/index.html": "projects/motorised-standing-desk/images/06-father-son-finished-top.jpg",
    "projects/msc-ai/index.html": "projects/msc-ai/images/robotics-rviz.jpg",
    "projects/robot-arm/index.html": "projects/robot-arm/images/07-cycloidal-joint-closeup.jpg",
    "projects/spiral-staircase/index.html": "projects/spiral-staircase/images/01-finished-staircase-full.jpg",
    "projects/vintage-string-lights/index.html": "projects/vintage-string-lights/images/01-finished-string-lights-wide.jpg",
}

# The MSc module pages all share the programme's images folder unless they have
# a figure of their own worth leading with.
MSC_PAGE_IMAGES = {
    "projects/msc-ai/data-mining-text-analytics/index.html": "dmta-generating-podcast.jpg",
    "projects/msc-ai/data-science/index.html": "data-science-output-02.jpg",
    "projects/msc-ai/deep-learning/index.html": "dl-encoder-decoder.jpg",
    "projects/msc-ai/knowledge-representation/index.html": "krr-sandwich-counterexample.jpg",
    "projects/msc-ai/machine-learning/index.html": "ml-mars-loops.jpg",
    "projects/msc-ai/mlx-course-projects/index.html": "mlx-course-architecture.jpg",
    "projects/msc-ai/programming-for-data-science/index.html": "p4ds-architecture-pipeline.jpg",
    "projects/msc-ai/robotics/index.html": "robotics-rviz.jpg",
}
for _page, _image in MSC_PAGE_IMAGES.items():
    PAGE_IMAGES[_page] = f"projects/msc-ai/images/{_image}"

PERSON_JSONLD = """    <script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "Person",
      "name": "Daniel Bryars",
      "url": "https://daniel.bryars.com/",
      "jobTitle": "Staff Engineer",
      "description": "Engineer, programmer and founder. Formula One R&D, a B2B SaaS company scaled and sold, an MSc in AI, and a workshop full of half-finished machines.",
      "address": { "@type": "PostalAddress", "addressLocality": "Oxford", "addressCountry": "GB" },
      "alumniOf": { "@type": "CollegeOrUniversity", "name": "University of Leeds" },
      "sameAs": [
        "https://github.com/DanielBryars",
        "https://www.linkedin.com/in/danielbryars/",
        "https://stackoverflow.com/users/418246/daniel-james-bryars"
      ]
    }
    </script>
"""


def canonical_for(page: Path) -> str:
    rel = page.relative_to(REPO).as_posix()
    if rel == "index.html":
        return f"{SITE}/"
    if rel.endswith("/index.html"):
        return f"{SITE}/{rel[: -len('index.html')]}"
    return f"{SITE}/{rel}"


def build_block(page: Path, title: str, description: str) -> str:
    rel = page.relative_to(REPO).as_posix()
    image = PAGE_IMAGES.get(rel, "images/og-cover.jpg")
    root = rel_url(page, REPO / "x")[:-1]  # relative prefix back to the repo root

    lines = [
        START,
        f'    <link rel="canonical" href="{canonical_for(page)}">',
        f'    <link rel="icon" href="{root}favicon.svg" type="image/svg+xml">',
        f'    <link rel="apple-touch-icon" href="{root}images/apple-touch-icon.png">',
        '    <meta name="theme-color" content="#10120f">',
        '    <meta name="author" content="Daniel Bryars">',
        '    <meta property="og:type" content="website">',
        '    <meta property="og:site_name" content="Daniel Bryars">',
        f'    <meta property="og:url" content="{canonical_for(page)}">',
        f'    <meta property="og:title" content="{escape(title, quote=True)}">',
        f'    <meta property="og:description" content="{escape(description, quote=True)}">',
        f'    <meta property="og:image" content="{SITE}/{image}">',
        '    <meta name="twitter:card" content="summary_large_image">',
        f'    <meta name="twitter:title" content="{escape(title, quote=True)}">',
        f'    <meta name="twitter:description" content="{escape(description, quote=True)}">',
        f'    <meta name="twitter:image" content="{SITE}/{image}">',
    ]
    if rel == "index.html":
        lines.append(PERSON_JSONLD.rstrip("\n"))
    lines.append(END)
    return "\n".join(lines)


def main() -> int:
    changed = 0
    for page in html_files():
        text = page.read_text(encoding="utf-8")

        title_match = TITLE_RE.search(text)
        desc_match = DESC_RE.search(text)
        if not title_match:
            print(f"  skip (no <title>): {page.relative_to(REPO)}")
            continue
        if not desc_match:
            print(f"  !! no meta description: {page.relative_to(REPO)}")
            continue

        title = unescape(title_match.group(1).strip())
        description = unescape(desc_match.group(1).strip())
        block = build_block(page, title, description)

        if BLOCK_RE.search(text):
            updated = BLOCK_RE.sub(lambda _: block.strip(), text, count=1)
        else:
            # Insert straight after the description tag so the head stays readable.
            insert_at = desc_match.end()
            insert_at = text.index("\n", insert_at) + 1
            updated = text[:insert_at] + block + "\n" + text[insert_at:]

        if updated != text:
            page.write_text(updated, encoding="utf-8")
            changed += 1
            print(f"  head {page.relative_to(REPO)}")

    print(f"{changed} page(s) updated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
